[v1]
"stdrename 1.1.0 (git+https://github.com/Gadiguibou/stdrename#af9acd6897781d0f799c7cbb7f502bc0b31c2e31)" = ["stdrename"]
"tpfancontrol 0.1.0 (git+https://github.com/Arnavion/tpfancontrol-rs#7219ad6fb239300e7bfa6286b6070434bf15b427)" = ["tpfancontrol"]
